{
 "title": "KServe ModelServer Latency",
 "description": "KServe's ModelServer Metrics Dashboard ",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Kserve Response Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "preprocess latency (ms)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(request_preprocess_seconds_bucket[5m]) * 1000) by (le)) * 1000",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(request_preprocess_seconds_bucket[5m]) * 1000) by (le)) * 1000",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_preprocess_seconds_bucket[5m]) * 1000) by (le)) * 1000",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_preprocess_seconds_bucket[5m]) * 1000) by (le)) * 1000",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "predict latency (ms)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(request_predict_seconds_bucket[5m])) by (le)) * 1000",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(request_predict_seconds_bucket[5m])) by (le)) * 1000",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_predict_seconds_bucket[5m])) by (le)) * 1000",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_predict_seconds_bucket[5m])) by (le)) * 1000",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "postprocess latency (ms)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(request_postprocess_seconds_bucket[5m]) * 1000) by (le)) * 1000",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(request_postprocess_seconds_bucket[5m]) * 1000) by (le)) * 1000",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_postprocess_seconds_bucket[5m]) * 1000) by (le)) * 1000",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_postprocess_seconds_bucket[5m]) * 1000) by (le)) * 1000",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "explain latency (ms)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(request_explain_seconds_bucket[5m])) by (le)) * 1000",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(request_explain_seconds_bucket[5m])) by (le)) * 1000",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_explain_seconds_bucket[5m])) by (le)) * 1000",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_explain_seconds_bucket[5m])) by (le)) * 1000",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Predict Total requests in last 24h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 17 },
   "targets": [
    {
     "expr": "increase(request_predict_seconds_count[24h])",
     "legendFormat": "{{ configuration_name }}"
    }
   ]
  }
 ]
}