---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: litellm
  namespace: ai-platform
spec:
  ingressClassName: public
  rules:
    - host: litellm.local.ro
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: litellm
                port:
                  name: http
