---
apiVersion: v1
kind: Namespace
metadata:
  name: ai-platform
  labels:
    pod-security.kubernetes.io/enforce: privileged
    purpose: platform-services
---
apiVersion: v1
kind: Namespace
metadata:
  name: inference
  labels:
    pod-security.kubernetes.io/enforce: privileged
    purpose: model-serving
---
apiVersion: v1
kind: Namespace
metadata:
  name: kserve
  labels:
    control-plane: kserve-controller-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: kro-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: hami-system
