---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger
  namespace: ai-platform
spec:
  ingressClassName: public
  rules:
    - host: jaeger.local.ro
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jaeger-query
                port:
                  name: query
