{
 "title": "KServe Torchserve Latency",
 "description": "KServe Torchserve Latency Dashobard ",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Kserve Response Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "inference latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(ts_inference_latency_microseconds[10m]) / 1000"
    }
   ]
  },
  {
   "title": "queue latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(ts_queue_latency_microseconds[10m]) / 1000"
    }
   ]
  },
  {
   "title": "Predict Total requests in last 24h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 9 },
   "targets": [
    {
     "expr": "increase(ts_inference_requests_total[24h])"
    }
   ]
  }
 ]
}